import type { Metadata } from "next";
import Provider from './provider';

import {DM_Sans } from "next/font/google";
import "./globals.css";
const AppFont=DM_Sans({subsets: ['latin']})
import {
  ClerkProvider
} from '@clerk/nextjs'

export const metadata: Metadata = {
  title: "AI Video Generator App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={AppFont.className}>
        <Provider>{children}</Provider>
        
      </body>
    </html>
    </ClerkProvider>
  );
}
